name: Registration Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  run-registration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Registration Test Class
        run: |
          # Add src folder in PYTHONPATH so that Python can find modules
          export PYTHONPATH=$PYTHONPATH:$(pwd)/ssqatest/src
          pytest tests/my_account/test_register_new_user.py::TestRegisterNewUser -v
