name: Run All Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"  # svaki dan u 9h UTC

jobs:
  run-all-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run all tests
        run: |
          # Add root folder repoa in PYTHONPATH so Python can find ssqatest package
          PYTHONPATH=$(pwd) python -m pytest tests -v
