name: Run All Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Create ssqatest package folder
        run: |
          mkdir ssqatest
          mv src tests ssqatest/

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest ssqatest/tests/ -v
